### ISSUE TITLE
Fix install script and push it up stream

### ISSUE THREAD

**Issue by iankronquist** [iankronquist/senior-project-experiment#15] opened 2016-04-21 20:07 UTC
1. Create a fresh ubuntu vm. It may be useful to create an [Ubuntu Vagrantfile](https://raw.githubusercontent.com/iankronquist/senior-project-experiment/903cab43f2c6390bcb556f788ec4e9a4b18a7591/Vagrantfile).
2. Clone the senior-project-experiment
3. Run, as root, our install script. Remember to provide it with the two arguments.
4. It's broken, I'm sure. Fix it.
5. Delete Ubuntu VM (vagrant destroy) and repeat steps 2-4 until it works.
6. Fork MHN and clone your fork.
7. Copy over our script and commit it into MHN. It should go in scripts.
8. Delete Ubuntu VM. Create a new Ubuntu VM.
9. Walk through the MHN install instructions and [install MHN](https://github.com/threatstream/mhn#installing-server-tested-ubuntu-12043-x86_64-and-centos-67) and [our honeypot](https://github.com/threatstream/mhn#deploying-honeypots-with-mhn)
10. Rinse and repeat from step 8 until it works smoothly.
11. Open PR. Fix anything which the MHN people ask for.

**Comment by pixel5919** [comment] 2016-04-26 00:31
Add you need to `export COMPOSE_API_VERSION=1.18`

**Comment by pixel5919** [comment] 2016-04-26 17:48
Line 5 in docker file is where the error is occurring
`RUN yum -y install httpd php php-mysql curl`

**Comment by pixel5919** [comment] 2016-04-26 19:05
The issue is with `RUN yum -y install http` it is a known bug in Dockerfile.

**Comment by iankronquist** [comment] 2016-04-27 00:58
@pixel5919 disabling AUFS seems to be sufficient to fix this. You just need to add this line to `/etc/default/docker`.
```
DOCKER_OPTS="--storage-driver=devicemapper"

```
Can you make the install script change the config file and then restart the Docker service?
```
service docker restart
```

**Comment by pixel5919** [comment] 2016-05-03 06:02
Okay now try it, I also updated #17

**Comment by pixel5919** [comment] 2016-05-04 05:30
Modern Honeypot Network is reviewing the pull request at https://github.com/threatstream/mhn/pull/270 closing the issue.

**Closed by pixel5919** 2016-05-04 05:30 UTC
Labels: bug, enhancement
